### ISSUE TITLE
Vertical vs. Horizontal bars

### ISSUE THREAD

**Issue by rbratslaver** [malcolmbarrett/designing.ggplots#3]
Hi - thanks so much for putting this content out there; I just had a really simple question I was hoping to run by you. In my local RStudio, the snippet below produces the default vertical bars whereas your slideshow has horizontal bars; can I ask how you got this behavior without any explicit code to change from vertical to horizontal bars? Thanks so much!
```
emperors %>%
  count(cause) %>%
  ggplot(aes(x = n, y = cause)) +
  geom_col()
```

<img width="239" alt="img" src="https://user-images.githubusercontent.com/32785182/69890809-ee0e6700-12c5-11ea-9fb1-bd9ffb57ecf9.PNG">

**Comment by malcolmbarrett** [comment]
yup! You need the development version of ggplot2. Use `remotes::install_github("tidyverse/ggplot2")`
